### ISSUE TITLE
Running source on startup of terminal in comparison to manually sourcing.

### ISSUE THREAD

**Issue by Relmnicoder** [kpbs5/ros2.fish#4]
Super big fan of what you have done here! Im super super thankful for this! So first of all thank you! :D <3

I had installed ros by building it from source, and so i had to change like two specific points for the entry points for the ros2 bin.
And currently i am unsure if i am pointing to the correct bin. 

If I manually source the built ./install/local_setup.bash with `bass source ./install/local_setup.bash` then when I run ros2 everything works perfectly fine, and tabs work, etc.

But if I let the fish file source it, no errors pop up during the sourcing, but as soon as I run any ros2 command I get this as an error
```
Traceback (most recent call last):
  File "/usr/lib64/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/relmnicoder/ros2_humble/install/ros2cli/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli', 'console_scripts', 'ros2')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/relmnicoder/ros2_humble/install/ros2cli/bin/ros2", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/metadata/__init__.py", line 861, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for ros2cli
```

Would you possibly have any clue as to why that would be? 

Just incase, the only parts that I modified are the parts where it references /opt/ros/humble into /home/relmnicoder/ros2_humble
and the ROS_DISTRO i just commented everything out except for  `set -gx ROS_DISTRO humble`.
And since the bin doesn't exist in the same place as if when you install it through the packages I use `set -g __fish_ros2 /home/relmnicoder/ros2_humble/install/ros2cli/bin/ros2`. 
That is one I am unsure if it is the correct thing to reference, especially since the error talks about ros2cli, but like I said, if I manually source later on then it just works, so I am a bit confused.

Once again Thank you, and if you don't know or this is a whole other issue that is fine too!
I sort of halfway wanted a reason just to say thanks for the fish scripts :D

**Comment by kpbaks** [comment]
Thank you for the kind words I really appreciate it!
I have not tried building ROS2 from source before. The scripts right now (naively) assume that you always install ROS2 from your platforms package distribution. I would like to improve this in the future. For the near future, 1 to 2 months, I do not have time to look at it, as I am writing my master thesis right now. 

Do you have a link with the instructions on how to build it from source?

**Comment by Relmnicoder** [comment]
https://docs.ros.org/en/humble/Installation.html Would be the site, and as I use Fedora I went to the alternatives and clicked on fedora. It runs mostly through, except for one or two times when you need to add an #include <cstdint> to the source, discussed here https://github.com/ros-tooling/libstatistics_collector/pull/183

Good luck with your master thesis!

**Comment by kpbaks** [comment]
Thank you
That will be a great help
